name: Build and Deploy SpotTheSpy Backend

on:
  push:
    tags:
      - 'main*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      docker:
        image: docker:28.0.1
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push docker image to GitHub Container Registry
        run: |
          REPOSITORY_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="${GITHUB_REF_NAME}"
          docker build -t ghcr.io/$REPOSITORY_NAME:$IMAGE_TAG .
          docker push ghcr.io/$REPOSITORY_NAME:$IMAGE_TAG

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry and Deploy to Server
        run: |
          REPOSITORY_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="${GITHUB_REF_NAME}"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.WORK_DIR }} 
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          export BACKEND_IMAGE="ghcr.io/${REPOSITORY_NAME}:${IMAGE_TAG}"
          docker compose pull
          docker compose up -d
          docker system prune -f
          docker image prune -a -f
          exit
          "

      - name: Cleanup SSH
        run: rm -rf ~/.ssh
